### PR TITLE
Fix marqo_settings schema & document names

### PR DESCRIPTION
**Pull request by MarvinZeising**
Hey,
we noticed some problems when trying to update the `hosts.xml` file for Vespa.
It complained that a `marqo__settings` schema would be dropped without recreation and that wouldn't be allowed.
After a bit of debugging I found that you're using `marqo__settings` [internally in Marqo](https://github.com/marqo-ai/marqo/blob/mainline/src/marqo/core/index_management/index_management.py#L38), and not `marqo_settings`.
Changing this in our configuration solved the problem for us.

### CODE REVIEW

**Comment by MarvinZeising** [comment]
Sorry, don't know why this was automatically closed...

**Comment by farshidz** [comment]
Hi @MarvinZeising . You are correct, Marqo uses `marqo__settings`. Could you please let me know why you are modifying `hosts.xml` and how you are doing so (i.e. how do you upload it back to Vespa)? I'm concerned that you will face a similar error after you create an index (because the schema corresponding to your index will be missing, instead of `marqo__settings`)

**Comment by ali60** [comment]
Hi @MarvinZeising ,
Thanks for sending this PR. As Farshid mentioned, we need more information. 
I'm trying to reproduce the issue. Can you help me with the following?

- What changes you wanted to make in hosts.xml?
- What error message do you see when Marqo is starting?
- Also, which cloud provider are you using?

Thanks!

**Comment by MarvinZeising** [comment]
Hi @farshidz and @ali60, thanks for your responses, much appreciated!

At first, we only had 1 feed node, 1 query node and 2 content nodes.
We had a short downtime when the Kubernetes cluster (on Azure) was upgraded, so now I want to update it to 3 nodes each.
So basically just adding more hosts like this:
```xml
<host name="vespa-query-2.vespa-query-headless.search.svc.cluster.local">
  <alias>query2</alias>
</host>
```

I added a version to the `services.xml`
```xml
<config name="container.handler.observability.application-userdata">
  <version>1</version>
</config>
```
And in my container startup script I'm using Vespa's `/ApplicationStatus` endpoint to check if the version is matching. If not (that is, if I have made changes and increased the version), it resends the application package to Vespa.

But that fails with Vespa saying the Application Package is invalid because the `marqo_settings` schema is dropped and the data in there would be lost. If you need the exact wording, I need to look that up because it's from two weeks ago.
Marqo starts just fine after that, but my Application Packages haven't been applied.

Do you have any tips for this case? (increasing the number of nodes, that is)

**Comment by ali60** [comment]
@MarvinZeising  today I created a cluster with default setting , then I increased the code count for `vespaquery`  , `vespafeed` and `vespaadmin` to 1 by editing [values](https://github.com/marqo-ai/marqo-on-kubernetes/blob/main/chart/marqo-kubernetes/values.yaml#L30-L39).  then applied kubectl again which worked for me on EKS.

So, it looks like you want to achieve high availability here, is that correct? If yes, I think increasing nodes and updating the `values.yaml` should work.

Regarding your solution, I'm still not sure why your configuration was not accepted. If this happens again, please send me the logs.

**Comment by MarvinZeising** [comment]
@ali60 thanks for trying it out. Super interesting that it works for you.

Just for my understanding: You updated the `values.yaml`, increasing the number of nodes. And then for Vespa to actually use these new nodes, did you also update the `hosts.xml` as well as the `services.xml` and then called the `/prepareandactivate` endpoint with the updated files?
Or did it work without that? If so, how does Vespa know about the new nodes?

**Comment by ali60** [comment]
@MarvinZeising sorry for my late response.
yes if you increase the nodes, then apply the template again , `host.xml` and `service.xml` will be updated this is the code which does that part:
https://github.com/marqo-ai/marqo-on-kubernetes/blob/main/chart/marqo-kubernetes/templates/marqo.yml#L60-L67

this is not dynamic, you have to run `kubectl apply ` to update the cluster with the new configuration.
Also you need to add nodes to you Azure clusters.

**Comment by MarvinZeising** [comment]
@ali60, hm okay. I'm still unsure why it's not working for us like it is for you, but that's okay for now.

This PR isn't valid then, right? Should I close it?

**Comment by ali60** [comment]
Thanks @MarvinZeising .
Yes we can close it for now

**Pull request closed without merging**
